2024-06-03 12:06:00,632 INFO    MainThread:44112 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-06-03 12:06:00,633 INFO    MainThread:44112 [wandb_setup.py:_flush():76] Configure stats pid to 44112
2024-06-03 12:06:00,633 INFO    MainThread:44112 [wandb_setup.py:_flush():76] Loading settings from /Users/rishubbhatia/.config/wandb/settings
2024-06-03 12:06:00,633 INFO    MainThread:44112 [wandb_setup.py:_flush():76] Loading settings from /Users/rishubbhatia/Documents/master thesis/Master-Thesis-GNN/wandb/settings
2024-06-03 12:06:00,633 INFO    MainThread:44112 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-03 12:06:00,633 INFO    MainThread:44112 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-03 12:06:00,633 WARNING MainThread:44112 [wandb_setup.py:_flush():76] Could not find program at -m games.pong.run_supervised
2024-06-03 12:06:00,633 INFO    MainThread:44112 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m games.pong.run_supervised'}
2024-06-03 12:06:00,633 INFO    MainThread:44112 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-03 12:06:00,633 INFO    MainThread:44112 [wandb_init.py:_log_setup():520] Logging user logs to /Users/rishubbhatia/Documents/master thesis/Master-Thesis-GNN/wandb/run-20240603_120600-1kln2gg8/logs/debug.log
2024-06-03 12:06:00,633 INFO    MainThread:44112 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/rishubbhatia/Documents/master thesis/Master-Thesis-GNN/wandb/run-20240603_120600-1kln2gg8/logs/debug-internal.log
2024-06-03 12:06:00,633 INFO    MainThread:44112 [wandb_init.py:init():560] calling init triggers
2024-06-03 12:06:00,633 INFO    MainThread:44112 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-06-03 12:06:00,633 INFO    MainThread:44112 [wandb_init.py:init():610] starting backend
2024-06-03 12:06:00,633 INFO    MainThread:44112 [wandb_init.py:init():614] setting up manager
2024-06-03 12:06:00,651 INFO    MainThread:44112 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-06-03 12:06:00,655 INFO    MainThread:44112 [wandb_init.py:init():622] backend started and connected
2024-06-03 12:06:00,672 INFO    MainThread:44112 [wandb_init.py:init():711] updated telemetry
2024-06-03 12:06:00,738 INFO    MainThread:44112 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-03 12:06:02,278 ERROR   MainThread:44112 [wandb_init.py:init():770] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-06-03 12:06:02,279 ERROR   MainThread:44112 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/Users/rishubbhatia/miniforge3/envs/games/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/Users/rishubbhatia/miniforge3/envs/games/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-06-03 12:06:03,863 WARNING MsgRouterThr:44112 [router.py:message_loop():77] message_loop has been closed
